# Default language (English)
en:
  languageCode: en-us
  title: "My Website"
  contentDir: content/en
  menu:
    main:
      - name: "Home"
        url: '/'
        weight: 1
      - name: "About"
        url: '/about/'
        weight: 2

ko:
  languageCode: ko
  contentDir: content/ko
  title: "내 웹사이트"
  params:
    description: "이것은 한국어 사이트입니다."
  menu:
    main:
      - name: "홈"
        url: '/'
        weight: 1
      - name: "소개"
        url: '/about/'
        weight: 2

ja:
  languageCode: ja
  contentDir: content/ja
  title: "私のウェブサイト"
  params:
    description: "これは日本語のウェブサイトです。"
  menu:
    main:
      - name: "ホーム"
        url: '/'
        weight: 1
      - name: "私たちについて"
        url: '/about/'
        weight: 2
