# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: ko
  #contentDir: content/ko

# Uncomment the lines below to configure your website in a second language.
ko:
  languageCode: en.us
  contentDir: content/en
  title: Chinese website title...
  params:
    description: Site description in Chinese...
  menu:
    main:
      - name: home
        url: '#about'
        weight: 1
