# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko
  contentDir: content/ko
  title: 박준영의 소개 사이트
  params:
    description: 박준영의 소개 사이트

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en.us
  contentDir: content/en
  title: June's introduction site
  params:
    description: June's introduction site
  menu:
    main:
      - name: bio
        url: '/authors/'
        weight: 1
      - name: project
        url: '/project/'
        weight: 2
