# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: about
    url: about
    weight: 10

  - name: profile
    url: /author/박준영/
    weight: 11

  - name: 정보
    url: experience
    weight: 20
  - parent: 정보
    name: 경력
    url: experience
    weight: 21
  - parent: 정보
    name: 동아리
    url: club
    weight: 22
  
  - name: study
    url: project
    weight: 30

  - name: info
    url: info
    weight: 40
